file(WRITE ${CMAKE_CURRENT_BINARY_DIR}/ar_input.txt "
  CREATE libchallenge.a.tmp
  ADDLIB ${TFLITE_PATH}
  ADDLIB ${OPENCV_PATH_CORE}
  ADDLIB ${OPENCV_PATH_HIGHGUI}
  ADDLIB ${OPENCV_PATH_IMGPROC}
  ADDLIB ${OPENCV_PATH_JPEG}
  ADDLIB ${OPENCV_PATH_PNG}
  ADDLIB ${OPENCV_PATH_TIFF}
  ADDLIB ${OPENCV_PATH_ZLIB}
  ADDLIB libchallenge.a
  SAVE
  END
")
